### ISSUE TITLE
Severe bug, missing elements

### ISSUE THREAD

**Issue by lokedhs** [jwiegley/red-black#2]
The following simple test case illustrates how members of the tree can randomly disappear when inserting and removing element from it:

```
(let* ((x (print (red-black:nil-tree)))
       (x (print (red-black:insert-item 4 x)))
       (x (print (red-black:insert-item 399/100 x)))
       (x (print (red-black:delete-item 4 x)))
       (x (print (red-black:insert-item 6 x)))
       (x (print (red-black:insert-item 599/100 x)))
       (x (print (red-black:delete-item 399/100 x))))
  x)
```

If you run this, you'll end up with an empty tree, even though you should have the elements `6` and `599/100`.

I've been looking at the code, but I'm having a hard time figuring out where the problem is.

**Comment by jwiegley** [comment]
Wow, good catch.  I was not the original author of that code, but I'm sure he'd like to know too.  It should be mentioned in the comments for that file.

**Comment by lokedhs** [comment]
I can't find any reference to the author in the source code.

I'm a bit concerned if this code is orphaned since it's on Quicklisp, and actually triggered a pretty severe issue in our application until it was discovered where the error was. If this isn't fixed then I'm sure there are other users that would suffer from similar problems.

**Comment by jwiegley** [comment]
Huh, your'e right, there's no mention whatsoever!

And yes, this package is most certainly orphaned.  I adopted the code in 2007, and have never modified it except to package it up for asdf.  If it's not working correctly, it should be deprecate and a better solution found.

**Comment by jwiegley** [comment]
The code came from here: http://www.aviduratas.de/lisp/lisp1.html

**Comment by lokedhs** [comment]
Would it make sense to take the library off Quicklisp until someone can fix it?

**Comment by jwiegley** [comment]
I would think so, yes.

**Comment by quicklisp** [comment]
Cambl depends on red-black. Should cambl be removed too?

**Comment by jwiegley** [comment]
And then you'll have to take out `cl-ledger` as well, if anyone is using that.

**Comment by lokedhs** [comment]
The package cl-containers contains a good red-black implementation. It's
the one I switched to after discovering that red-black didn't work. Its API
is also much better.

I'd be willing to create a wrapper around it that provides the same API as
red-black so it can be a drop-in replacement.

Or course, the ideal situation is if the dependent systems can be fixed. I
could submit patches for the two systems that depends on red-black, if
we're sure these are the only ones.

**Comment by jwiegley** [comment]
I'm not sure if other authors had started using red-black or not, but its incorrect behavior surely means that it should be disabled.  A wrapper interface for cl-containers sounds like a great way to move people to that library quickly.

**Comment by lokedhs** [comment]
I'll take a look at it and see if I can easily make one.

**Comment by lokedhs** [comment]
I've started working on the wrapper library. Will any of you be able to check if the dependent systems will work with this wrapper?

**Comment by quicklisp** [comment]
I can check that things build, but not that they work beyond that.

**Comment by lokedhs** [comment]
The `LEFT` and `RIGHT` functions of red-black is somewhat hard to emulate effectively without calling into internal functions of cl-containers. I would much rather see these two projects that use red-black be updated to use cl-containers directly instead.

@jwiegley would it make sense for you to make that change? I believe both of these projects are yours?

**Comment by jwiegley** [comment]
I haven't used Common Lisp in years, so it can't depend on me to make that change.  `cl-ledger` is even abandonware now, so if you want to exclude all of my packages, I'm fine with that too.

**Comment by quicklisp** [comment]
I think I'll pull everything, for now. Better to have it unavailable than broken & orphaned. Maybe it will be adopted in the future.

**Comment by christophejunke** [comment]
@quicklisp `cambl` is now using `cl-containers` instead of `red-black`. I also updated `cl-ledger`. Both projects, `cambl` and `cl-ledger`, load without error from my `local-projects` (tested with SBCL, ECL and CCL). I think they could  be made available again in a future release of quicklisp, if you don't mind.

**Comment by quicklisp** [comment]
@christophejunke Do you want to be the new maintainer of those projects? If so, that works for me.

**Comment by christophejunke** [comment]
@quicklisp Yes, John let me be the maintainer of the `periods`, `cambl` and `cl-ledger` packages.

**Comment by quicklisp** [comment]
Ok, does that mean I should pull them from new locations?

**Comment by christophejunke** [comment]
You can keep pulling from their current locations (e.g. git://github.com/jwiegley/cl-ledger.git), because I have write access to the existing repositories.

**Comment by quicklisp** [comment]
Ok, thanks. Can you please add :description, :author, and :license metadata to cambl and cl-ledger?

**Comment by christophejunke** [comment]
Done.
